* Hyper-go notes: 
     * Issues and proposed solutions 
     * Comments on GO terms and structure 
     * Developer thought (DT)


** GO-ChEBI cross-references 

  * GO-plus ontology: includes cross ontology relationships, including Chebi. However, it seems that the linkage was based on string matching only. The linking between GO and chebi represented in the "Cross-Ontology Relations" section in GO, represents a relation between each term in GO with the corresponding term in ChEBI. However, it is not always accurate and not all GO terms being linked with chebi terms. reference http://discovery.ucl.ac.uk/1436778/1/1471-2164-14-513.pdf
  
  For example:
   + methylgalactoside transmembrane transporter GO:0015592
   + e.x: GO:0015134 hexuronate transmembrane transporter activity  mapped with hexuronic acid.
   + e.x: GO:0015229 L-ascorbicAcid
   + e.x: GO:0000100
   + e.x: GO:0034590
   + e.x: GO:1901236


 
** General issue

Information in GO about each term is scarce. 

Most of GO terms names are defined generally, while Chebi ontology is more specific in defining terms. 

 * For example: + GO:0015087  cobalt ion transmembrane transporter activity. In Chebi there are: cobalt(1+), cobalt(2+), cobalt(3+), cobalt_cation. Same case for other terms.
 
 * For example: + GO:0015445  silver-exporting ATPase activity: enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O + Ag+(in) -> ADP + phosphate + Ag+(out). 
   
-GO term name: silver ion (broad)
-GO term from its defintion: silver(1+)
In chebi: there are  - silver ion  - silver cation - silver(1+)

It is not enough to link the GO term with the equivalent chebi term only by name matching. We have to know the GO name and definition to be able to link it with the right term in chebi. 

GO-plus ontology: includes cross ontology relationships, including Chebi. However, it seems that the linkage was based on name matching only.

 * Terms not found in ChEBI:
   + Basic amino acid	(DV) mapped to ch/amino_acid and add a property hasAcidity alkaline (Defined)
   + Neutral amino acid	(DV) mapped to ch/amino_acid and add a property hasAcidity Neutral  (Defined)
   + Acidic amino acid	(DV) mapped to ch/amino_acid and add a property hasAcidity Acidic   (Defined)
   + Sugar              NOT DEFINED YET : look like sugar in GO immaterial concept !      (NOT Defined)
   + lactoferrin    GO:0033569 : define new class as a subclass of ch/protein    (Defined)          
   + Transferrin    GO:0033570 : define new class as a subclass of ch/iron_3+_   (Defined)
   + Copper chelate GO:0051981 : define new class as a subclass of ch/copper_cation (Defined)
   + copper-nicotianamine GO:0051982 : define new class as a subclass of the CopperChelate. (Defined)
   + alkanesulfonate GO:0042959
   + colicin transmembrane transporter GO:0042912  and group A colicin GO:0042913 : https://mailman.stanford.edu/pipermail/go-ontology/2013-February/002885.html
   + adhesin autotransporter activity GO:0015475 : define new class as a subclass of ch/chemical_entity  (Defined)
   + hemaglutinin autotransporter activity GO:0015476 :(DV) hemaglutinin: refers to glycoproteins which cause red blood cells (RBCs) to agglutinate (from https://en.wikipedia.org/wiki/Hemagglutinin). So this term mapped to glycoprotein CHEBI:17089. (Defined)
   + sodium-dependent multivitamin transmembrane transporter activity GO:0008523: (DV): looks like it's an immaterial concept, the cargo is either pantothenate, biotin and lipoate. (Defined)
   + eye pigment precursor GO:0005395  (NOT Defined)
   + GO:0008982	protein-N(PI)-phosphohistidine-sugar phosphotransferase activity: because sugar not defined in ChEBI
   
  
 * GO Incorrect classification
   + The (GO:0015513) high-affinity secondary active nitrite transmembrane transporter activity, classified as is_a nitrate transmembrane transporter activity GO:0015112, which I think it is not correct.The GO:0015513 is_a  GO:0015113 not GO:0015112
   +  GO:0009977 proton motive force dependent protein transmembrane transporter activity: classified in GO as primary and secondary active transporter. !!

** Diff classification between GO and ChEBI

  * In many cases a term in GO has no role or some roles, whereas in ChEBI has some extra roles, for example:
     +  GO:1905131 and GO:0034634
  * In many cases a term in GO has some role, but in Chebi the term do not have that role, has some other roles, for example:
     +  acridine transmembrane GO:0042911
     + benomyl transmembrane transporter GO:1901479
     
 
  
  * In GO: hexuronate transmembrane transporter activity GO:0015134 is_a uronic acid . In ChEBI they are two different terms: hexuronate and hexuronic acid, the latter is_a  uronic acid. hexuronate is conjugate base of hexuronic acid and therefore it is conjugate base of uronic acid.
  
  * In GO: threonine efflux transmembrane GO:0015565 is a L-threonine transmembrane GO:0015195. In ChEBI it is the opposite. \\
   (DV): It might be a mistake in GO where they wrote threonine instead of L-threonine, becasue (in GO) GO:0015195 is a L-amino acid and it is the same in ChEBI L-threonine is L-apha_amino_acid. GO:0015565 is an amino_acid. 
   (DV): define the term GO:0015565 as L-threonine not as threonine.

  * In GO: GO:0042878 D-glucarate, In ChEbi D-glucarate(1-) and D-glucarate(2-). (DV): based on "Cross-Ontology Relations" in GO,  it is D-glucarate(2-).
  
  * In GO: S-methylmethionine GO:0000100 represented as one term, whereas In chebi there are two terms S-methylmethionine and S-methyl-L-methioninate. GO:0000100 is a modified amino acid and sulfur molecular entity --> In chebi S-methyl-L-methioninate is a modified amino acid while S-methyl-L-methionine is a sulfur molecular entity. (DV) define the term as S-methylmethionine
 
  * GO:0015233 pantothenate is conjugate base of (R)-pantothenic acid which is conjugate acid of the pantothenate. \\ (DV): I defined the term as (R)-pantothenic acid, NOT as (R)-pantothenate.
  
   * Long-chain fatty acid (GO:0005324) is NOT subclass of Fatty acid, whereas in ChEBI Long-chain fatty acid is a subclass of Fatty acid. (DT) ChEBI classification looks more accurate.

 * In GO some chemical entities classified as the same (exact), whereas in ChEBI there are some distinctions:
     + e.x: in GO: GO:0015373 anion classified as monovalent anion (exact). In ChEBI: monovalent inorganic anion is any inorganic anion with a valency of one.
     + e.x: GO:0015487 inorganic cation classified as monovalent cation (exact). In ChEBI: monovalent inorganic cation:  positive charge that does not contain carbon in covalent linkage, with a valency of one.

 * GO:1902417 (+)-abscisic acid D-glucopyranosyl ester transmembrane  is_a glucoside. In ChEBI is_a D-glucoside -> glucoside -> carbohydrate_derivative
   + Same for GO:0042951

 * GO:0005371 tricarboxylate secondary active is as conjugate base of GO:0015142 tricarboxylic acid transmembrane; not direct is_a subclass based on ChEBI.


* GO classification errors
   + GO:0015395 classified as Secondary Active transporter, whereas it should be classified as passive diffusion based on its definition. Based on this http://europepmc.org/abstract/MED/10353709 , it classified as passive diffusion.
   
 * dehydroascorbic acid transmembrane transporter GO:0033300 in GO has role vitamin, which is not the case in ChEBI. However, in ChEBI  L-dehydroascorbic acid CHEBI:27956 has role vitamin. L-dehydroascorbic acid is_a dehydroascorbic acid.
 
 * peptidoglycan transmembrane transporter GO:0015647 and peptidoglycan peptide transmembrane transporter GO:0015640: represented in one class in ChEBI as CHEBI:8005.
 
 * acriflavine transmembrane transporter GO:0015566
 
 * GO:0097364  involved in regulation of action potential, in GO linked with GO:0001508 action potential. It should be linked with GO:0098900 regulation of action potential.
 * GO:0097365 involved in regulation of cardiac muscle cell action potential, in GO linked with GO:0086001. It should be linked with  GO:0098901 regulation of cardiac muscle cell action potential


** Are they the same ?
    + sodium-dependent L-ascorbate transmembrane transporter activity  GO:0070890   and \\ 
      L-ascorbate:sodium symporter activity  GO:0008520. (DV): from thier definitions in GO, there is no difference.
   
    + Efflux and Export : Both from the inside of the cell to the outside.
    
    + translocating and transporting: GO:0046623 sphingolipid-translocating ATPase activity. 


** High/Low Affinity
A substance or substances transported with high and low affinity such as zinc ions.

(DT): High and low affinity are properties of the transporter not the cargo.
      Define a property BindingAffinity which will be a value-partition with highaffinity and lowaffinity.

ISSUE: In the case that the same chemical element transported once in high affinity and later in low affininty, linking those with same term from chebi ontology cause ontology inconsistent

CAUSE: Ontology inconsistenc, due to linking the same concept (i.e. chebi term) via the same object property to different values in a value partition.

SOLUTION: Define an object property (called transports-with) for the transported, not the thing being transported (cargo).

** Transporting molecules driven by ATPase

ATPase activity: directly drive the active transport of a substance across a membrane. 

Terms under this pattern are transported either from the inside of the cell to the outside and and vice versa.

(DT): define a pattern for all substances that driven directly by the ATPase.

ISSUES:

Different term naming schema between GO and chebi. 
 * For example:  + GO:0015408   Ferric-transporting ATPase activity. 
		 CHEBI:29034  iron(3+)
		 + GO:0015625    ferric-hydroxamate-transporting ATPase activity.  
		 Chebi:  iron_III__hydroxamate

 * َSome terms in GO can be found as a synonyms in ChEBI, such as  (GO) Quaternary amine = (ChEBI) Quaternary ammonium ion

** Transporting/Exporting/Importing driven by ATPase

ATPases are a class of enzymes that catalyze the decomposition of ATP into ADP and a free phosphate ion. 

All of the following are primary active transmembrane transporter that are driven by ATP energy (ATPase):

chemical_entity-transporting
chemical_entity-importing
chemical_entity-exporting

** Active transport

Active transport: moves material from area of low concentration to area of higher concentration, and therefore referred to as moving the material "against the concentration gradient"

Most of GO terms do not specify what is the source of energy: 
 + active borate transmembrane transporter activity GO:0046715 is an active but does not tell by which molecule is driven by. (According to this: Park, M., Li, Q., Shcheynikov, N., Zeng, W. and Muallem, S., 2004. NaBC1 is a ubiquitous electrogenic Na+-coupled borate transporter essential for cellular boron homeostasis and cell growth and proliferation. Molecular cell, 16(3), pp.331-341.) It is sodium ion Na+

However, these clearly specified the energy source as proton:
 + zinc efflux active transmembrane transporter activity GO:0015341 : from the term definition its driven by proton motive force.
 + GO:0009977
 + GO:0005427
 + GO:0022897

** Primary Active transmembrane transporter

Primary active transport is catalysis of the transport of a solute across a membrane.

In primary active transport, the energy is derived directly from the breakdown of ATP into ADP and a Phosphate group (it hydrolyses it), called ATPase.

Example: 
	1.To pump the sodium ion out of the cell against its concentration gradient (sodium ions already have a high concentration outside the cell).
	2.Use ATP
	3.Breaks ATP into ADP and a Phosphate group (it hydrolyses it), called ATPase
	4.Uses that energy (ATPase) to pump the sodium ion out of the cell and potassium into the cell
	5.The pumped-out sodium form a potential energy which can later be used to power a SECONDARY Active transport. 

Primary active: (Antiporter)
Both substances (sodium ion and potassium) going against their concentration gradient.

I think: 
 * In GO: the antiporter called -exchanging, that is only with: sodium/proton: potassium-exchanging. 
   However, the different between antiporters in Primary and Secondary active transporter is the substances in the Primary are both going against their concentration gradient.
   
Secondary active (Antiporter)

One substance going with its concentration gradient and the other substance going against its concentration gradient.

 ** Diff between ATP and ATPase 
   +ATP synthase generate more ATP whereas as ATPase breaks apart ATP releasing energy to drive forward reactions that are not very spontaneous (can't happen on their own).

** Secondary Active transmembrane transporter, Antiporter and Symporter 

In Secondary active transport a substance is pumped from a region (outside or inside of the cell) of lower concentration to a region of higher concentration. 
This process requires energy which does not come directly from ATP rather it comes from the energy stored in the substance gradient which was created using ATP. 

ISSUES:
	* From the definition of the Secondary Active in GO, does not specify which substance has lower concentration and high concentration (which one is the cargo and which is th energy).
	Example from GO: nucleoside transmembrane transporter activity, against a concentration gradient, GO:0011074 
 	
	* In GO: Uniporter Activity (GO:0015292) stated to be a secondary transporter. However it is a Passive transport, particularly facilitated diffusion transport 
	Uniporter is an integral memebrane protein involved in facilitated diffusion
	Uniporters rely on passive transport, as they do not directly require cellular energy to function.

According to this: http://www.physiologyweb.com/lecture_notes/membrane_transport/secondary_active_transport.html
    
   * Transporter protein couples the movement of an ion (typically Na+ or H+) down its electrochemical gradient to the uphill movement of another molecule 
     or ion against a concentration/electrochemical gradient.
   * Sodium serves as the driving ion in many (but not all) secondary active transporters located in the plasma membrane of various cells.

Antiporter and Symporter
  * Sodium is the driving ion for many Symporter and antiporter. Not sure this is the case in GO .!!!

  * Usually two solutes
  * But there is symporter with more than two solutes : GO:0008511 sodium:potassium:chloride symporter activity

** Passive transporter

  * "Passive diffusion moves materials from an area of higher concentration to an area of lower concentration, it is described as moving solutes "down the concentration gradient"
  * For molecules to transport in passive form:
      + Small and does not have a charge, for example carbon dioxide, molecular oxygen and water

** Channel activity
  
  * Allow passage of solutes through a transmembrane aqueous Pore or Channel.
  * Channel opens in response to a specific stimulus such as: 
      + voltage, ligand, specific ion, specific biologicalprocess and specific molecule.
  * Gap junctions: are channels between adjacent cells (cell-to-cell only) that allow for the transport of ions, nutrients, and other molecules.
  * Gap junctions: directly connect the cytoplasm of two cells which allow molecules to pass through regulated gate between cells
  
  
  * calcium activated cation channel activity
  * calcium-activated potassium channel activity GO:0015269:  
   + Ca2+-activated K+ channels are a diverse group of channels that are activated by an increase in intracellular Ca2+ concentration.
   + Source: http://www.ebi.ac.uk/interpro/entry/IPR003930   and  http://europepmc.org/abstract/MED/9687354
  
  
  * voltage-gated channels: response to changes in the electric potential difference in the voltage difference between the two sides of the membrane. I think it means, response to electrical stimulus GO:0051602.
  
  * voltage-gated ion channel Any ion channel that opens and closes in response to changes in electrical potential across the cell membrane in which the channel is situated

 * Ligand Gated Ion Channels also know as ionotropic receptors
 * what is An ionotropic receptors (e.x ionotropic glutamate receptor) ?
   + They are proteins that are sitting within the cell membrane.
   + Allow ions; sodium ion, potassium ions, chloride ions, calcium ions, cations, etc.to move through them, when they are open.


** What is Membrane Potential (Em)?
  * It is the charge across the memebrane.
 * What is the Cell Resting Potential ?
  + The voltage difference between intracellular space and the extracellular space when a neuron is in non activated state (resting state).
  + The resting membrane potential of neuron ranges between negative 50 and negative 80 millivolts (mV).
  + The resting potential is the electrical charge that the cell has when it is resting and not stimulated by any open ion channels.
  + The cell is in its resting state the channels are closed,but still leaky and ions move in and out of the cell.
  + The electrical charge inside the cell is more negative than outside the cell becasue of the high concentration of sodium outside the cell, inside the cell are more potassium ions but also negatively charged proteins.
 
** What is Action Potential?
  + The cell membrane is filled with ion channels that allow ions to enter the cell when stimulated by Action potential.
  + The voltage difference between the inside of the cell and the outside will allow the cell to receive electrical signals known as "Action Potential".
  + The Action Potential is created becasue of the concentration difference of ions between the intracellular space and the extracellular space (there is a higher concentration of sodium ions outside the neuron and high concentration of potassium inside;
the extracellular space is more positive than inside the neuron; this creates voltage difference of -70 mV which created by leaky ions and channels that are more permeable to potassium ions than sodium ions)
  + When the cell membrane stimulated by some action potential it causes sodium Na+ channel to open, letting in positive ions --> this change the electrical enviroment  and make it more positive inside the cell and less positive outside, this is called "Depolarization".
  + Depolarization: make the electrical enviroment more positive inside the cell
  + Repolarization: the intracellular space became negative again.
  + Hyper-polarization: too negative in the intracellular space when the cell pumped out too many ions (more negative than resting potential), this is corrected by leaky ion channels and sodium potassium pump to reach the minus 70 mV, the resting state.

** What is Donnan Equilibrium(Eion)?
  * It is the membrane potential at which the movement into the cell EQUALS the movement out of the cell.
  * For example: The Donnan Equilibrium for Sodium NA+ (Ena) is 58mV, if the Membrane Potential is at 58mV NA+ is relaxed.


** What is a Ligand in Cell Biology?
  * Small molecules that transmit signals in between or within cells.
  * Ligands bind to cellular proteins called receptors which send the received signals to other parts of the cell.
  * Tow types: intracellular ligands(bind to receptors inside the cell) and extracellular ligands (bind to receptors outside the cell).
  * In general: ligand is an ion, molecule, or molecular group that binds to another chemical entity to form a larger complex.

** Others
  * GO:0022880 : This differs from primary and secondary active transport in that the solute is modified during transport. 

What is inward rectification (Kir)?
   * allow large positive charge inward direction (into the cell) than in the outward direction (out of the cell).
   * inwardly rectifying K+ channels support the flow of positively charged K+ ions into the cell, pushing the membrane potential back to the resting potential.
   *  inwardly-rectifying potassium channels: have evolved distinct voltage-independent mechanisms for opening and closing, including gating by G proteins, pH and ATP.


** Chemical Role

 * Chemical role in GO:
    1. drug
    2. vitamine
    3. cofactor
    4. coenzyme
    5. xenobiotic
    6. neurotransmitter
    7. Siderophore : classified in more detailed in ChEBI whereas in GO just as role
    
   * There are some terms in GO classified as is_a drug, whereas in ChEbi they are not. For example: 
       + GO:0015141 succinate transmembrane transporter activity is_a a drug in GO, whereas in ChEBI it is not, but it is conjugate base of succinate(1−) which in turn is is conjugate base of succinic acid that has_role drug.
       + GO:0042878 (smae case of above)
       + GO:0015549 has role drug in GO but not in ChEBI 
    
  * GO:0042895 Antibiotic transmembrane transporter, What is the equivalent term in ChEBI ?
     + antimicrobial agent http://purl.obolibrary.org/obo/CHEBI_33281      OR 
     + antimicrobial drug http://purl.obolibrary.org/obo/CHEBI_36043       OR

Agent: antimicrobial agent is NOT a subclass of drug CHEBI:23888 \\
Drug:  antimicrobial drug is a subclass of drug CHEBI:23888 

However: 
   * There are some terms in GO that is_a Antibiotic, but in ChEBI has_role antimicrobial agent
       + e.x: GO:0042897  - GO:0042898 - GO:0015638 - GO:0022885
       
   *  There are some terms in GO that is_a Antibiotic, and in ChEBI has_role both antimicrobial agent and antimicrobial drug
       + e.x: GO:0008493 tetracycline  -  GO:0042896 - GO:0015244 - GO:1901479 - GO:0015547
       + e.x: GO:0015243 has different roles such as: biological and application roles.
       
   * There are some terms in GO that is_a Antibiotic, but in ChEBI has No role Antibiotic
      + e.x: GO:0015499 formate  is conjugate base of formic acid which has_role antibacterial agent
      + e.x: GO:0015552 propionate is conjugate base of propionic acid which has_role antifungal drug that is both antibacterial agent and drug.
      + e.x: GO:0042925  (same above)
     
   * In some cases a term in GO has some role, but in Chebi the term do not have that role. However, the ACID of that term match the GO classification (has the same role in GO or more specific role)
     + In GO propionate transmembrane transporter GO:0015552 has role antibiotic (antibiotic = antimicrobial_drug), Whereas in ChEBI it is not. The GO:0015552 is conjugate base of Propionic Acid which has role antifungal drug that is_a drug, but not antimicrobial_drug. (DV) define the term as Propionic Acid becuase it matches GO classification (has role drug and is_a a short-chain fatty acid (CHEBI:26666)
     + GO:0015306 N-acetylneuraminate (Sialate) In GO has role antibiotic, in ChEBI it is conjugate base of N-acetylneuraminic acid which has role antimicrobial_drug. (DV) define the term as N-acetylneuraminic acid.
     

 * GO:0042910 xenobiotic transmembrane transporter What is the equivalent term in ChEBI ?
   +  xenobiotic http://purl.obolibrary.org/obo/CHEBI_35703
   +  human xenobiotic metabolite CHEBI:76967
   
   + e.x: GO:0015244   has role xenobiotic
   + e.x: GO:0042926  has role human xenobiotic metabolite 
   + e.x: GO:0005368  is_a xenobiotic in GO, but not in ChEBI
   + e.x: GO:0015566  is_a xenobiotic in GO, but not in ChEBI
   + e.x: GO:0042911  is_a xenobiotic in GO, but not in ChEBI

  * xenobiotic transmembrane transporter activity (GO:0042910)  is NOT a drug
  * xenobiotic transmembrane transporter activity (GO:0008559)  has role some drug,   Is this an enzyme EC 3.6.3.44 ?  Catalysing transmembrane movement of substances


 * siderophore transmembrane transporter GO:0015343 What is the equivalent term in ChEBI ?
   +  siderophore (CHEBI:26672) 
   + Fe(III)-complexed hydroxamate siderophore (CHEBI:84688)  
   
   + e.x: GO:0042933  has role siderophore
   + e.x: GO:0042929  is a Fe(III)-complexed hydroxamate siderophore 


** Catalytic Activity (CA)

 * Statistics and ontological nature of CA classes
   + Total number of classes in CA: 7001
   + Total number of classes in CA not include classes from TA (already defined): 6837 
   + Most of the terms in CA are about chemical reacions, start their definition with "Catalysis of the reaction: substance + substance = substance + substance". The initial total number is: 4332
   + The chemical reactions classified to four main groups depend on the type of reaction: oxidoreductase activity (2097), transferase activity(2097), hydrolase activity(1555), lyase activity (576), isomerase activity(246) and other small group (cyclase activity (27), demethylase activity (23))
	
 * Databases for chemical reactions
   + There are other databases mainly about chemical reactions such as EC, MetaCyc, KEGG and Rhea
   + Rhea is an expert curated resource of biochemical reactions designed for the annotation of enzymes and genome-scale metabolic networks and models.
   + Rhea uses the ChEBI (Chemical Entities of Biological Interest) ontology of small molecules to precisely describe reactions participants and their chemical structures.
	
 * Reaction Directionality
   + Allmost al the terms in CA identifying reactions and have an unspecified/unknown (=) direction.
   + In Rhea aach master reaction is associated to unspecified/unknown (=) and 3 directional reactions. Ref: https://www.rhea-db.org/documentation;jsessionid=EC317FA2C6507CCABE0CF3F0E688D35F
   + We need to design the pattern that identify the terms with the (=) direction, however, some terms such as: GO:0036456 and GO:0033744 with same reaction participants but different direction

 * Challenges:
    * Within GO itself same entity but different representation. For example:
      + FADH2 - FADH(2)
      + H2O - H(2)O
      + H+ - H(+)
      + NADP+ - NAD(P)+
      + coumaroyl-CoA - 4-coumaroyl-CoA
      + CO2 - carbon dioxide
  
 * Not all CA chemical reactions classes has reference to Rhea or, we have to find out: 
   + GO:0002948 --> RHEA:54084 && GO:0001888 --> RHEA:16224 && GO:0003755 --> RHEA:16237 && GO:0003810 --> RHEA:43771 && GO:0030743 --> RHEA:43212 && GO:0016436 --> RHEA:43184 && GO:0016437 --> RHEA:14433 && GO:0008825 --> RHEA:11991 && GO:0047144 --> RHEA:14236 && GO:1990259 --> RHEA:50904 && GO:0033801 --> RHEA:11435 && GO:000888 -->  RHEA:18592 && GO:0033837 --> RHEA:35628 && GO:0033830 --> RHEA:17841 && GO:0102511 --> RHEA:35434 && GO:0008412 --> RHEA:27782 && GO:0030792 --> RHEA:11685 && GO:0047946 --> RHEA:18472 && GO:0008353 --> RHEA:10219 && GO:0047961 --> RHEA:19872 && GO:0050313 --> RHEA:12984 && GO:0004457 --> RHEA:23447 && GO:0047137 --> RHEA:13116  && GO:0004455 --> RHEA:22071 && GO:0008805 --> RHEA:13984 && GO:0052580 --> RHEA:25644 && GO:0052579 --> RHEA:25647 && GO:0018678 --> RHEA:16388 && GO:0008874 --> RHEA:23938 && GO:0052590 --> RHEA:28756 && GO:0052589 --> RHEA:30095 && GO:0018665 --> RHEA:15160 && GO:0003908 --> RHEA:24000 && GO:0033786 --> RHEA:27465 && GO:0033785 --> RHEA:27473 && GO:0003968 --> RHEA:21251 && GO:0036408 --> RHEA:21992 && GO:0052908 --> RHEA:19609 && GO:0052909 --> RHEA:42780 && GO:0003976 --> RHEA:13584 && (GO:0050316 --> RHEA:13517 & RHEA:12697) && (GO:0004674 --> RHEA:46608 & RHEA:17989) && GO:0003956 --> RHEA:19152 & GO:0004851 --> RHEA:32459 && GO:0018708 --> RHEA:18280 && GO:0015667 --> RHEA:16857 && GO:0033094 --> RHEA:12271 && GO:0047286 --> RHEA:11820 && GO:0052622 --> RHEA:36331 && GO:0047284 --> RHEA:18361 && GO:0047281 --> RHEA:10232 && GO:0052623 --> RHEA:36327 && GO:0052624 --> RHEA:40551 && GO:0061599 --> RHEA:35047 && GO:0047297 --> RHEA:19813 && GO:0047293 --> RHEA:17709 && GO:0047291 --> RHEA:18417 && GO:0047228 --> RHEA:17285 && GO:0004579 --> RHEA:22980 && GO:0004578 --> RHEA:13865 && GO:0008951 --> RHEA:44012
   
 * General terms in GO (does not have particular molecule from the ChEBI):
   + GO:0050316
   + GO:0050321
   + GO:0016427 : tRNA containing methylcytosine not in ChEBI, only tRNA containing 5-methylcytosine exists but it is more relevant to GO:0016428
   + GO:0016426 : (same above) tRNA containing methyladenine not in ChEBI, only tRNA_containing_N_1_-methyladenine exists but it is more relevant to GO:0016429
   + GO:0034212 : the chemical equation is general, defined based on GO definition (an amino acid residue) and the chebi representation. (N-acetylpeptide --> N-terminal alpha-amino-acid residue)

 * GO (Cross-references) is not always accurate. e.g:
   + GO:0052589 linked to RHEA:46015, where it sould be linked to RHEA:30095
   
 * Different representation of terms between the 3 ontologies (GO, Rhea and ChEBI)
   + GO:0004173 (palmitoyl-CoA), Rhea (hexadecanoyl-CoA), ChEBI (palmitoyl-CoA(4-))
      
 * GO terms created based on self reading and external reference due to lack of info in GO: e.g
   + GO:0016401 (trans-2_3-dehydropalmitoyl-CoA): https://v12.chemtunes.com/biopath3/biopath/mols/trans-Hexadec-2-enoyl-CoA
   + GO:0001734 : RRACH is not one particular molecule. RRACH: (R represents purine, A is m6A and H is a non-guanine bas)
   ref: http://europepmc.org/articles/pmc5410061
   
 * The linkage between Rhea and Chebi is not based on "string matching". e.g
    + GO:0047931 - RHEA:10948 ( D-glucosamine and D-glucosamine 6-phosphate)
 
 
 * Specific substances not defined in ChEBI,represented in Rhea as generic terms: molecules that is not represented as is in ChEBI.
    + GO:0052906 --> RHEA:36902 and GO:0052905 --> RHEA:4315: They linked to the same substances from Chebi
    + GO:0052916 --> RHEA:42745 and GO:0052913 --> RHEA:23549: They linked to the same substances from Chebi
 
 * Terms in GO general, but in Rhea is specific
    + GO:0047284 (protein) --> RHEA:18361 (L-serine residue)
