* Hyper-go notes: 
     * Issues and proposed solutions 
     * Comments on GO terms and structure 
     * Developer thought (DT)


 * GO-ChEBI mapping \\
  There is "Cross-Ontology Relations" in GO to map GO terms with ChEBI terms, but it is not always accurate.
   + e.x: GO:0015134 hexuronate transmembrane transporter activity  mapped with hexuronic acid.
   + e.x: GO:0015229 L-ascorbicAcid

** General issue

The information in GO about each term is scarce. 

Most of GO terms names are defined generally, while Chebi ontology is more specific in defining terms.

It is not enough to link the GO term with the equivalent chebi term only by name matching. We have to know the GO name and definition to be able to link it with the right term in chebi. 

GO-plus ontology: includes cross ontology relationships, including Chebi. However, it seems that the linkage was based on name matching only.

 * Terms seems not exist in ChEBI:
   + Basic amino acid	(DV) mapped to amino acid with acidity alkaline
   + Neutral amino acid	(DV) mapped to amino acid with acidity Neutral
   + Acidic amino acid	(DV) mapped to amino acid with acidity Acidic
   + Sugar              NOT DEFINED YET : look like sugar in GO immaterial concept compare to ChEBI..! 
 
 
 * Diff classification between GO and ChEBI
  + In GO: hexuronate transmembrane transporter activity GO:0015134 is a hexuronic acid. In ChEBI they are two different terms.
  
  + In GO: threonine efflux transmembrane GO:0015565 is a L-threonine transmembrane GO:0015195. In ChEBI it is the opposite. \\
   (DV): There might be a mistake in GO where they wrote threonine instead of L-threonine, becasue (in GO) GO:0015195 is a L-amino acid and it is the same in ChEBI L-threonine is L-apha_amino_acid. GO:0015565 is an amino_acid. \\
   (DV): define the term GO:0015565 as L-threonine not as threonine.

  + In GO: GO:0042878 D-glucarate, In ChEbi D-glucarate(1-) and D-glucarate(2-)
  (DV): based on "Cross-Ontology Relations" in GO,  it is D-glucarate(2-).

 * Are they the same ?
  + sodium-dependent L-ascorbate transmembrane transporter activity  GO:0070890   and \\ 
    L-ascorbate:sodium symporter activity  GO:0008520 \\ (DV): from thier definitions in GO, there is no difference.
   
  + Efflux and Export : Both from the inside of the cell to the outside.

** High/Low Affinity
A substance or substances transported with high and low affinity such as zinc ions.

(DT): High and low affinity are properties of the transporter not the cargo.
      Define a property BindingAffinity which will be a value-partition with highaffinity and lowaffinity.

ISSUE: In the case that the same chemical element transported once in high affinity and later in low affininty, linking those with same term from chebi ontology cause ontology inconsistent

CAUSE: Ontology inconsistenc, due to linking the same concept (i.e. chebi term) via the same object property to different values in a value partition.

SOLUTION: Define an object property (called transports-with) for the transported, not the thing being transported (cargo).

** Transporting molecules driven by ATPase

ATPase activity: directly drive the active transport of a substance across a membrane. 

Terms under this pattern are transported either from the inside of the cell to the outside and and vice versa.

(DT): define a pattern for all substances that driven directly by the ATPase.

ISSUES:

Different term naming schema between GO and chebi. 
 * For example: -GO:     Ferric-transporting ATPase activity
		-Chebi:  iron(3+)
		-GO:     ferric-hydroxamate-transporting ATPase activity
		-Chebi:  iron_III__hydroxamate

GO term is a broad where chebi term is narrow:
 * For example: -GO:   cobalt-transporting ATPase activity
		-Chebi cobalt_cation  (there is no term cobalt by it

 * For example:  GO:  silver-exporting ATPase activity: enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O + Ag+(in) -> ADP + phosphate + Ag+(out). 
   
-GO term name: silver ion (broad)
-GO term from its defintion: silver(1+)
In chebi: there are  - silver ion  - silver cation   - silver(1+)

 * َSome terms in GO can be found as a synonyms in ChEBI, such as  (GO) Quaternary amine = (ChEBI) Quaternary ammonium ion
 * 

** Transporting/Exporting/Importing driven by ATPase

All of the following are primary active transmembrane transporter that are driven by ATP energy (ATPase):

chemical_entity-transporting
chemical_entity-importing
chemical_entity-exporting

** Active transport
 
 Primary active or Secondary active transmembrane transporter

** Primary Active transmembrane transporter

Primary active transport is catalysis of the transport of a solute across a membrane.

In primary active transport, the energy is derived directly from the breakdown of ATP into ADP and a Phosphate group (it hydrolyses it), called ATPase.

Example: 
	1.To pump the sodium ion out of the cell against its concentration gradient (sodium ions already have a high concentration outside the cell).
	2.Use ATP
	3.Breaks ATP into ADP and a Phosphate group (it hydrolyses it), called ATPase
	4.Uses that energy (ATPase) to pump the sodium ion out of the cell and potassium into the cell
	5.The pumped-out sodium form a potential energy which can later be used to power a SECONDARY Active transport. 

Primary active: (Antiporter)
Both substances (sodium ion and potassium) going against their concentration gradient.

I think: 
 * In GO: the antiporter called -exchanging, that is only with: sodium/proton: potassium-exchanging. 
   However, the different between antiporters in Primary and Secondary active transporter are substances in the Primary are both going against their concentration gradient.
   
Secondary active (Antiporter)

One substance going with its concentration gradient and the other substance going against its concentration gradient.

** Secondary Active transmembrane transporter, Antiporter and Symporter 

In Secondary active transport a substance is pumped from a region (outside or inside of the cell) of lower concentration to a region of higher concentration. 
This process requires energy which does not come directly from ATP rather it comes from the energy stored in the substance gradient which was created using ATP. 

ISSUES:
	* From the definition of the Secondary Active in GO, does not specify which substance has lower concentration and high concentration (which one is the cargo and which is th energy).
	Example from GO: nucleoside transmembrane transporter activity, against a concentration gradient, GO:0011074 
 	
	* In GO: Uniporter Activity (GO:0015292) stated to be a secondary transporter. However it is a Passive transport, particularly facilitated diffusion transport 
	Uniporter is an integral memebrane protein involved in facilitated diffusion
	Uniporters rely on passive transport, as they do not directly require cellular energy to function.

See this: http://www.physiologyweb.com/lecture_notes/membrane_transport/secondary_active_transport.html
    
   * Transporter protein couples the movement of an ion (typically Na+ or H+) down its electrochemical gradient to the uphill movement of another molecule 
     or ion against a concentration/electrochemical gradient.
   * Sodium serves as the driving ion in many (but not all) secondary active transporters located in the plasma membrane of various cells.

Antiporter and Symporter
  * Sodium is the driving ion for many Symporter and antiporter.


** Chemical Role


 * Chemical role in GO:
    1. drug
    2. vitamine
    3. cofactor
    4. coenzyme
    5. xenobiotic
    6. neurotransmitter

  * xenobiotic transmembrane transporter activity (GO:0042910)  is NOT a drug
  * xenobiotic transmembrane transporter activity (GO:0008559)  has role some drug,   Is this an enzyme EC 3.6.3.44 ?  Catalysing transmembrane movement of substances
