* Hyper-go notes: 
     * Issues and proposed solutions 
     * Comments on GO terms and structure 
     * Developer thought (DT)


** GO-ChEBI linking \\
  There is "Cross-Ontology Relations" in GO, represent a relation between each term in GO with the ChEBI term, but it is not always accurate.
   + e.x: GO:0015134 hexuronate transmembrane transporter activity  mapped with hexuronic acid.
   + e.x: GO:0015229 L-ascorbicAcid
   + e.x: GO:0000100
   + e.x: GO:0034590
   + e.x: GO:1901236


 
** General issue

The information in GO about each term is scarce. 

Most of GO terms names are defined generally, while Chebi ontology is more specific in defining terms. 

 * For example: + GO:0015087  cobalt ion transmembrane transporter activity. In Chebi there are: cobalt(1+), cobalt(2+), cobalt(3+), cobalt_cation. Same case for other terms.
 
 * For example: + GO:0015445  silver-exporting ATPase activity: enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O + Ag+(in) -> ADP + phosphate + Ag+(out). 
   
-GO term name: silver ion (broad)
-GO term from its defintion: silver(1+)
In chebi: there are  - silver ion  - silver cation - silver(1+)

It is not enough to link the GO term with the equivalent chebi term only by name matching. We have to know the GO name and definition to be able to link it with the right term in chebi. 

GO-plus ontology: includes cross ontology relationships, including Chebi. However, it seems that the linkage was based on name matching only.

 * Terms seems not to exist in ChEBI:
   + Basic amino acid	(DV) mapped to amino acid with acidity alkaline
   + Neutral amino acid	(DV) mapped to amino acid with acidity Neutral
   + Acidic amino acid	(DV) mapped to amino acid with acidity Acidic
   + Sugar               NOT DEFINED YET : look like sugar in GO immaterial concept !
   + lactoferrin    GO:0033569
   + Transferrin    GO:0033570
   + Copper chelate GO:0051981
   
 * GO Incorrect classification
   + The (GO:0015513) high-affinity secondary active nitrite transmembrane transporter activity, classified as is_a nitrate transmembrane transporter activity GO:0015112, which I think it is not correct.The GO:0015513 is_a  GO:0015113 not GO:0015112

** Diff classification between GO and ChEBI

  * In many cases a term in GO has no role or some roles, whereas in ChEBI has some extra roles. 
     + For example GO:1905131 and GO:0034634
  
  * In GO: hexuronate transmembrane transporter activity GO:0015134 is_a uronic acid . In ChEBI they are two different terms: hexuronate and hexuronic acid, the latter is_a  uronic acid. hexuronate is conjugate base of hexuronic acid and therefore it is conjugate base of uronic acid.
  
  * In GO: threonine efflux transmembrane GO:0015565 is a L-threonine transmembrane GO:0015195. In ChEBI it is the opposite. \\
   (DV): It might be a mistake in GO where they wrote threonine instead of L-threonine, becasue (in GO) GO:0015195 is a L-amino acid and it is the same in ChEBI L-threonine is L-apha_amino_acid. GO:0015565 is an amino_acid. 
   (DV): define the term GO:0015565 as L-threonine not as threonine.

  * In GO: GO:0042878 D-glucarate, In ChEbi D-glucarate(1-) and D-glucarate(2-). (DV): based on "Cross-Ontology Relations" in GO,  it is D-glucarate(2-).
  
  * In GO: S-methylmethionine GO:0000100 represented as one term, whereas In chebi there are two terms S-methylmethionine and S-methyl-L-methioninate. GO:0000100 is a modified amino acid and sulfur molecular entity --> In chebi S-methyl-L-methioninate is a modified amino acid while S-methyl-L-methionine is a sulfur molecular entity. (DV) define the term as S-methylmethionine
 
  * GO:0015233 pantothenate is conjugate base of (R)-pantothenic acid which is conjugate acid of the pantothenate. \\ (DV): I defined the term as (R)-pantothenic acid, NOT as (R)-pantothenate.
  
   * Long-chain fatty acid (GO:0005324) is NOT subclass of Fatty acid, whereas in ChEBI Long-chain fatty acid is a subclass of Fatty acid. (DT) ChEBI classification looks more accurate.

 * In GO some chemical entities classified as the same (exact), whereas in ChEBI there are some distinctions:
     + e.x: in GO: GO:0015373 anion classified as monovalent anion (exact). In ChEBI: monovalent inorganic anion is any inorganic anion with a valency of one.
     + e.x: GO:0015487 inorganic cation classified as monovalent cation (exact). In ChEBI: monovalent inorganic cation:  positive charge that does not contain carbon in covalent linkage, with a valency of one.

 * GO:1902417 (+)-abscisic acid D-glucopyranosyl ester transmembrane  is_a glucoside. In ChEBI is_a D-glucoside -> glucoside -> carbohydrate_derivative
   + Same for GO:0042951

  * GO:0005371 tricarboxylate secondary active is as conjugate base of GO:0015142 tricarboxylic acid transmembrane; not direct is_a subclass based on ChEBI.


  * GO classification
   + GO:0015395 classified as Secondary Active transporter, whereas it should be classified as passive diffusion based on its definition.



** Are they the same ?
    + sodium-dependent L-ascorbate transmembrane transporter activity  GO:0070890   and \\ 
      L-ascorbate:sodium symporter activity  GO:0008520. (DV): from thier definitions in GO, there is no difference.
   
    + Efflux and Export : Both from the inside of the cell to the outside.
    
    + translocating and transporting: GO:0046623 sphingolipid-translocating ATPase activity. 


** High/Low Affinity
A substance or substances transported with high and low affinity such as zinc ions.

(DT): High and low affinity are properties of the transporter not the cargo.
      Define a property BindingAffinity which will be a value-partition with highaffinity and lowaffinity.

ISSUE: In the case that the same chemical element transported once in high affinity and later in low affininty, linking those with same term from chebi ontology cause ontology inconsistent

CAUSE: Ontology inconsistenc, due to linking the same concept (i.e. chebi term) via the same object property to different values in a value partition.

SOLUTION: Define an object property (called transports-with) for the transported, not the thing being transported (cargo).

** Transporting molecules driven by ATPase

ATPase activity: directly drive the active transport of a substance across a membrane. 

Terms under this pattern are transported either from the inside of the cell to the outside and and vice versa.

(DT): define a pattern for all substances that driven directly by the ATPase.

ISSUES:

Different term naming schema between GO and chebi. 
 * For example:  + GO:0015408   Ferric-transporting ATPase activity. 
		 CHEBI:29034  iron(3+)
		 + GO:0015625    ferric-hydroxamate-transporting ATPase activity.  
		 Chebi:  iron_III__hydroxamate

 * َSome terms in GO can be found as a synonyms in ChEBI, such as  (GO) Quaternary amine = (ChEBI) Quaternary ammonium ion

** Transporting/Exporting/Importing driven by ATPase

All of the following are primary active transmembrane transporter that are driven by ATP energy (ATPase):

chemical_entity-transporting
chemical_entity-importing
chemical_entity-exporting

** Active transport

Active transport: moves material from area of low concentration to area of higher concentration, and therefore referred to as moving the material "against the concentration gradient"

Most of GO terms do not specify what is the source of energy: 
 + active borate transmembrane transporter activity GO:0046715 is an active but does not tell by which molecule is driven by. (According to this: Park, M., Li, Q., Shcheynikov, N., Zeng, W. and Muallem, S., 2004. NaBC1 is a ubiquitous electrogenic Na+-coupled borate transporter essential for cellular boron homeostasis and cell growth and proliferation. Molecular cell, 16(3), pp.331-341.) It is sodium ion Na+

However, these clearly specified the energy source as proton:
 + zinc efflux active transmembrane transporter activity GO:0015341 : from the term definition its driven by proton motive force.
 + GO:0009977
 + GO:0005427
 + GO:0022897

** Primary Active transmembrane transporter

Primary active transport is catalysis of the transport of a solute across a membrane.

In primary active transport, the energy is derived directly from the breakdown of ATP into ADP and a Phosphate group (it hydrolyses it), called ATPase.

Example: 
	1.To pump the sodium ion out of the cell against its concentration gradient (sodium ions already have a high concentration outside the cell).
	2.Use ATP
	3.Breaks ATP into ADP and a Phosphate group (it hydrolyses it), called ATPase
	4.Uses that energy (ATPase) to pump the sodium ion out of the cell and potassium into the cell
	5.The pumped-out sodium form a potential energy which can later be used to power a SECONDARY Active transport. 

Primary active: (Antiporter)
Both substances (sodium ion and potassium) going against their concentration gradient.

I think: 
 * In GO: the antiporter called -exchanging, that is only with: sodium/proton: potassium-exchanging. 
   However, the different between antiporters in Primary and Secondary active transporter is the substances in the Primary are both going against their concentration gradient.
   
Secondary active (Antiporter)

One substance going with its concentration gradient and the other substance going against its concentration gradient.

 ** Diff between ATP and ATPase 
   +ATP synthase generate more ATP whereas as ATPase breaks apart ATP releasing energy to drive forward reactions that are not very spontaneous (can't happen on their own).

** Secondary Active transmembrane transporter, Antiporter and Symporter 

In Secondary active transport a substance is pumped from a region (outside or inside of the cell) of lower concentration to a region of higher concentration. 
This process requires energy which does not come directly from ATP rather it comes from the energy stored in the substance gradient which was created using ATP. 

ISSUES:
	* From the definition of the Secondary Active in GO, does not specify which substance has lower concentration and high concentration (which one is the cargo and which is th energy).
	Example from GO: nucleoside transmembrane transporter activity, against a concentration gradient, GO:0011074 
 	
	* In GO: Uniporter Activity (GO:0015292) stated to be a secondary transporter. However it is a Passive transport, particularly facilitated diffusion transport 
	Uniporter is an integral memebrane protein involved in facilitated diffusion
	Uniporters rely on passive transport, as they do not directly require cellular energy to function.

According to this: http://www.physiologyweb.com/lecture_notes/membrane_transport/secondary_active_transport.html
    
   * Transporter protein couples the movement of an ion (typically Na+ or H+) down its electrochemical gradient to the uphill movement of another molecule 
     or ion against a concentration/electrochemical gradient.
   * Sodium serves as the driving ion in many (but not all) secondary active transporters located in the plasma membrane of various cells.

Antiporter and Symporter
  * Sodium is the driving ion for many Symporter and antiporter. Not sure this is the case in GO .!!!

  * Usually two solutes
  * But there is symporter with more than two solutes : GO:0008511 sodium:potassium:chloride symporter activity

** Passive transporter

  * "Passive diffusion moves materials from an area of higher concentration to an area of lower concentration, it is described as moving solutes "down the concentration gradient"


** Others
  * GO:0022880 : This differs from primary and secondary active transport in that the solute is modified during transport. 

** Chemical Role

 * Chemical role in GO:
    1. drug
    2. vitamine
    3. cofactor
    4. coenzyme
    5. xenobiotic
    6. neurotransmitter
    7. Siderophore : classified in more detailed in ChEBI whereas in GO just as role
    
   * There are some terms in GO classified as is_a drug, whereas in ChEbi they are not. For example: 
       + GO:0015141 succinate transmembrane transporter activity is_a a drug in GO, whereas in ChEBI it is not, but it is conjugate base of succinate(1−) which in turn is is conjugate base of succinic acid that has_role drug.
       + GO:0042878 (smae case of above)
    
  * GO:0042895 Antibiotic transmembrane transporter, What is the equivalent term in ChEBI ?
     + antimicrobial agent http://purl.obolibrary.org/obo/CHEBI_33281      OR 
     + antimicrobial drug http://purl.obolibrary.org/obo/CHEBI_36043       OR

Agent: antimicrobial agent is NOT a subclass of drug CHEBI:23888 \\
Drug:  antimicrobial drug is a subclass of drug CHEBI:23888 

However: 
   * There are some terms in GO that is_a Antibiotic, but in ChEBI has_role antimicrobial agent
       + e.x: GO:0042897  - GO:0042898 - GO:0015638 - GO:0022885
       
   *  There are some terms in GO that is_a Antibiotic, and in ChEBI has_role both antimicrobial agent and antimicrobial drug
       + e.x: GO:0008493 tetracycline  -  GO:0042896 - GO:0015244 - GO:1901479 - GO:0015547
       + e.x: GO:0015243 has different roles such as: biological and application roles.
       
   * There are some terms in GO that is_a Antibiotic, but in ChEBI has No role Antibiotic
      + e.x: GO:0015499 formate  is conjugate base of formic acid which has_role antibacterial agent
      + e.x: GO:0015552 propionate is conjugate base of propionic acid which has_role antifungal drug that is both antibacterial agent and drug.
      + e.x: GO:0042925  (same above)


 * GO:0042910 xenobiotic transmembrane transporter What is the equivalent term in ChEBI ?
   +  xenobiotic http://purl.obolibrary.org/obo/CHEBI_35703
   +  human xenobiotic metabolite CHEBI:76967
   
   + e.x: GO:0015244   has role xenobiotic
   + e.x: GO:0042926  has role human xenobiotic metabolite 
   + e.x: GO:0005368  is_a xenobiotic in GO, but not in ChEBI
   + e.x: GO:0015566  is_a xenobiotic in GO, but not in ChEBI
   + e.x: GO:0042911  is_a xenobiotic in GO, but not in ChEBI

  * xenobiotic transmembrane transporter activity (GO:0042910)  is NOT a drug
  * xenobiotic transmembrane transporter activity (GO:0008559)  has role some drug,   Is this an enzyme EC 3.6.3.44 ?  Catalysing transmembrane movement of substances


 * siderophore transmembrane transporter GO:0015343 What is the equivalent term in ChEBI ?
   +  siderophore (CHEBI:26672) 
   + Fe(III)-complexed hydroxamate siderophore (CHEBI:84688)  
   
   + e.x: GO:0042933  has role siderophore
   + e.x: GO:0042929  is a Fe(III)-complexed hydroxamate siderophore 


